DEFAULT_ABTESTING_ANDROID_RUNNING = 'false'
DEFAULT_ABTESTING_IOS_RUNNING = 'false'

ABTESTING = {
    androidRunning: ENV['ABTESTING_ANDROID_RUNNING'] || DEFAULT_ABTESTING_ANDROID_RUNNING,
    iosRunning: ENV['ABTESTING_IOS_RUNNING'] || DEFAULT_ABTESTING_IOS_RUNNING
}
