DEFAULT_ANDROID_MV = '1.0.0'
DEFAULT_ANDROID_LV = '1.0.0'
DEFAULT_IOS_MV = '1.0.0'
DEFAULT_IOS_LV = '1.0.0'
DEFAULT_API_SM = 'false'
DEFAULT_UPGRADE_TITLE = "Upgrade your App"
DEFAULT_UPGRADE_MESSAGE = "<b>We recently launched a new feature</b>"

RESOURCES_META_PATH = "CloudBoxAPIResourcesMeta"
RESOURCES_DATA_PATH = "CloudBoxAPIResourcesData"

DEFAULT_ABTESTING_ANDROID_RUNNING = 'false'
DEFAULT_ABTESTING_IOS_RUNNING = 'false'
